openapi: 3.0.0
info:
  title: Tennis Index General API
  version: 1.0.0
  description: Tennis Index Pro
tags: []
paths: {}
security:
  - BearerAuth: []
components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
